"""
inject_cjk.py — 把 cjk_font16.vh 的 case 表嵌入 osd_banner.v 的标记区
幂等：重复运行会整块替换。标记:
  // >>> CJK-ROM-BEGIN ... // <<< CJK-ROM-END
"""
import re, io

VH = r"C:\td_batch\lab_pro\user_source\hdl_source\cjk_font16.vh"
V  = r"C:\td_batch\lab_pro\user_source\hdl_source\osd_banner.v"

BEGIN = "    // >>> CJK-ROM-BEGIN"
END   = "    // <<< CJK-ROM-END"

vh = io.open(VH, encoding="utf-8").read()
# 取 function...endfunction，整体缩进4格（放模块内）
m = re.search(r"(function \[15:0\] cjk16;.*?endfunction)", vh, re.S)
assert m, "vh 里没找到 cjk16 function"
body = "\n".join(("    " + ln) if ln.strip() else ln for ln in m.group(1).splitlines())
block = BEGIN + " (auto-generated by tools/inject_cjk.py, 勿手改) >>>\n" + body + "\n" + END

src = io.open(V, encoding="utf-8").read()
if BEGIN.split()[2] in src:  # 已有标记 -> 整块替换
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    src = pat.sub(block, src)
else:                        # 首次 -> 插在 ASCII 字体 function 结束(endfunction)之后的行
    anchor = src.index("    endfunction\n", src.index("function [7:0] glyph8x16"))
    pos = anchor + len("    endfunction\n")
    src = src[:pos] + "\n" + block + "\n" + src[pos:]
io.open(V, "w", encoding="utf-8").write(src)
print("[OK] 已注入 %d 行到 osd_banner.v" % (block.count("\n") + 1))
